### ISSUE TITLE
System Capstone

### ISSUE THREAD

**Issue by renzcast** [NewFolder14/IPT2-CASE_STUDY#10]
Ano pang gagawin ko? @rowel1925

tapos na ako sa checkout page

Pero yung add to cart na check out Hindi pa, kasi hindi ko alam yung checkbox..

**Comment by rowel1925** [comment]
Mali ung input mo, Login page ininput mo hindi checkout page
paki check

**Comment by NewFolder14** [comment]
The page issue has been resolved.
